### ISSUE TITLE
DVRUI_Upcoming called w/o 2nd param in search.php

### ISSUE THREAD

**Issue by airdrummer** [demonrik/HDHR-DVRUI#4]
PHP Warning:  Missing argument 2 for DVRUI_Upcoming::DVRUI_Upcoming(), called in /Users/dvr/DVR/webAccess/HDHR-DVRUI/search.php on line 70 and defined in /Users/dvr/DVR/webAccess/HDHR-DVRUI/includes/dvrui_upcoming.php on line 38

fix dvrui_upcoming.php on line 38:
	public function DVRUI_Upcoming($hdhr, $recordings = NULL) {

**Comment by demonrik** [comment]
Good catch, however fix suggestion is in the wrong location.

dvrui_upcoming.php in normal operation checks if a recording already exists when doing the upcoming.. search.php is using a loophole in the functions to flush the upcoming cache - so it should pass a null for recordings because it KNOWS it's not going to go further with the use of the the Upcoming helper.
i.e. dvrui_upcoming.php can't assume that no-one is actually going to ask it to it's work!

so fix will be to modify line 70 of search.php
from
		$hdhrUpcoming = new DVRUI_Upcoming($hdhr);
to
		$hdhrUpcoming = new DVRUI_Upcoming($hdhr, null);

Can either create a pull request.. Or I will attempt to get the patch made by end of today anyway.

**Comment by airdrummer** [comment]
ah, tricky;-) go ahead w/ur fix, haven't quite grokked git yet...shoulda: i worked 4 a guy who had commit privs on git;-)
